/**
 * Help text carried forward from the classic CustomTkinter UI.
 * Keep parameter explanations aligned with kohya_core/configs.py PARAM_TIPS and
 * KohyaLoRATool._attach_main_tooltips / _attach_adv_tooltips.
 */
export const legacyTooltips = {
  mode: '训练目标影响标签整理与预设：画风侧重绘画风格，人物侧重目标角色，概念侧重指定特征。已配置的参数不会全部被切换覆盖，请核对当前值；模式不保证只学习某一种特征。',
  atSubMode: '人物=保留全部标签；画风=过滤人物标签；概念=形态/种族（trigger 吸收原型）。',
  baseModel: '底模架构需与所选权重匹配。选择文件后尝试自动识别，无法确定时请手动确认；各架构的环境和显存需求见当前模式说明。',
  rawDir: '放原始图片的文件夹（支持 jpg/png/webp/bmp/tif/gif）。',
  chooseRawDir: '选择原始图片文件夹。',
  preprocess: '图像模式会整理并打标图片；第三引擎 H3 视频模式只检查字幕；H3 Fizgig 混合媒体模式只扫描，不移动或转码。',
  labelEditor: '打开标签编辑器：逐张看图改标签、批量删除/替换标签、置顶 trigger、标签频率统计、整理成 repeats_名称 子目录结构。训练前改好标签，模型学得更准。',
  openOutput: '打开训练产物目录：模型、使用模板、参数报告、中间快照。',
  readme: '打开新手教学 & 常见问题窗口。',
  modelHelp: '查看模型选择步骤、本地模型目录格式、训练流程和显存建议。',
  trigger: '触发词=模型的“召唤词”：人物模式=角色名；画风模式=画风专属词。训练后画图写上它就能唤出角色/画风。支持多个，用英文逗号分隔。',
  regDir: '正则数据集：用于保留底模原有类别表现的额外图片（可选），应与训练目标和标签策略匹配；不是简单再放一组同角色图片，也不保证防止过拟合。',
  chooseRegDir: '选择正则数据集文件夹（人物模式可选）。',
  stylePreset: '出图风格：只在「模式+底模」基线学习率上做微调（动漫将预设学习率降低 15%，写实提高 15%；不保证改善清晰度、自然度或避免过拟合）。rank / alpha / repeats / epoch 仍按训练模式和底模自动填；选「写实」还会切换打标兜底描述与成品文件名。',
  styleCaption: '画风描述词：留空使用当前标签策略；填写后用于支持模式的画风描述和默认采样提示词，不保证效果提升。',
  conceptType: '选择要学习的概念类型；下方会显示该类型对应的数据集准备建议。',
  cleanConcept: '删掉描述这个概念本身的标签（如 black jacket / long sleeves / zipper），让触发词独占它。',
  strongBind: '自动把 trigger + 训练集 100% 一致的特征词固定到标签开头。',
  samplePreview: '训练中采样预览：自动档在显存低于 20GB 时关闭；手动开启仍会尝试采样。额外省显存档的自动策略可能关闭采样，手动开启可覆盖；缺少必需预览模型时无法出图。采样需额外显存，开训前会显示本次规则。',
  samplePrompt: '留空=按当前模式生成默认提示词（人物、画风、概念及媒体模式各有不同）；填入整句则优先使用，是否包含 trigger 由你决定。',
  cropRatio: '默认不裁切（保比例，人脸不易被切）；可输入自定义宽:高，如 2:3。',
  wd14Model: '选择自动打标模型。首次使用会下载，之后离线可用。',
  overwrite: '勾选后：重新生成图片并重读你现在的标签（源文件夹里的 .txt）。\n不勾选（默认）：输出目录里已经处理过的图会整张跳过，你在源文件夹里改的标签不会被采用。\n\n什么时候需要勾：手动改过标签、用外部/别的打标模型重写过标签，或想换裁切比例 / 分辨率重新出图时。',
  rank: 'LoRA rank：决定可训练参数容量。增大通常增加显存和文件大小，不保证更像或更清晰；需结合数据和训练量选择。',
  alpha: 'LoRA alpha：与 rank 一起影响训练更新的缩放。模式预设各有不同，不等同于出图时的 LoRA 加载权重。',
  unet_lr: 'UNet 学习率：控制参数更新幅度，不代表每步运行速度。适合的数值取决于底模、优化器和数据；实际学习率还受预热与调度影响。',
  te_lr: '文本编码器学习率：仅在文本编码器参与训练时生效。通常采用较低起始值；不同优化器不能直接比较数值。',
  unetOnly: '只训练 UNet：冻结文本编码器，其学习率不生效；通常减少可训练参数与显存开销，不保证效果更好。',
  repeats: '图片重复次数：增加每轮中同一图片的出现次数。与样本数、轮数和批大小共同决定训练量；增加不保证效果更好。',
  maxEpochs: '最大训练轮数：轮数越多学得越久，够用就好。',
  resolution: '训练分辨率：分辨率越高，显存和时间开销通常越大。默认 512；请结合底模、素材和显存自行调高。部分模式会按引擎要求对齐数值。',
  videoSteps: '总训练步数：步数越多训练越久，也可能过拟合。H3 视频模式上限 3000；Qwen-Image / Z-Image 上限 6000；具体以开训确认页为准。',
  videoFrames: '第三引擎 H3 视频帧数需符合 17n+5；H3 Fizgig 的帧数设置只影响预览采样，不会裁剪训练视频。',
  fizgigQwenPreset: 'Fizgig 官方 Qwen-Image-2.1 预设固定 rank、alpha 和学习率；Fast 的学习率会在 2e-4~4e-4 内自适应。Auto 按画风/人物/概念类型选择预设。',
  fastTier: 'Z-Image 自动档在显存低于 10GB 时启用；Qwen-Image 需手动开启。该省显存档会量化文本编码器、启用层交换，自动档会关闭训练采样；手动开启可覆盖采样策略。该档可能让每步更慢，训练分辨率仍按你填写的值。',
  optimizer: '自动=按环境预检选 AdamW8bit 或降级；若报 bitsandbytes 崩溃，改选 AdamW/Lion。第四引擎目前由训练入口指定优化器，页面不提供无效的手动选择。',
  quantMode: '按当前训练引擎选择支持的底模精度；bf16 通常更吃显存。',
  blocksToSwap: '自动=按显存档位；0=全部驻留显存；块越少越快但越吃显存。',
  batchSize: '每步同时训练的图片数。留空 = 自动（1）。调大后每轮步数会相应减少（每轮步数 = repeats × 图片数 ÷ 批大小），显存占用上升；显存吃紧请保持 1。',
  gradientCheckpointing: '自动 = 显存小于 16GB 时开启。开启省显存但每步更慢；关闭更快，但显存占用明显增加（块交换/分辨率高时容易爆显存）。',
  compile: '模型编译：启动阶段可能较慢，也会增加资源开销；当前入口在显存不足时可能禁用。是否支持与是否生效以启动日志为准。',
  noiseOffset: '噪声偏移：训练时给随机噪声做一点调整，可能影响暗部和整体明暗对比。当前 0.05 是推荐值；新手保持不变即可。',
  minSnrGamma: 'Min-SNR gamma：平衡模型在不同训练噪声阶段的学习权重。当前 5 是推荐值；新手保持不变即可，它不是清晰度或训练轮数设置。',
  globalPos: '附加全局正向提示词：训练时自动加到每张图片标签最前面（例如 masterpiece），不写进图片的 txt 文件，可留空。',
  globalNeg: '附加全局负向提示词：会写进使用模板和参数报告；kohya 训练本身不使用负向提示词，可留空。',
  saveEverySteps: '这些模式按步保存；留空/0 = 每 200 步。第一引擎的保存间隔最低为 50 步。',
  saveEveryEpochs: '本引擎按「轮」保存：直接填轮数，填 1 = 每轮都存；留空=默认每 1 轮。填得比总轮数还大时，一次快照都不会存。',
  sampleIntervalSteps: '填 N = 每 N 步采样；留空/0 时，Kohya 与 musubi 跟随保存节奏，AI Toolkit 每 250 步。训练开始时可能额外采样。',
  sampleIntervalEpochs: '本引擎按轮采样：填 N = 每 N 轮；留空/0 会按图集大小估算约每 100 步一次，至少每 1 轮。实际间隔以开训确认页和日志为准。',
  amdMode: 'AMD 兼容模式（实验性）：按当前引擎检查对应环境并使用 AMD 训练配置。第三引擎需安装独立 ROCm 环境；第一引擎可指定训练 venv。',
  trainEnv: '仅第一引擎 AMD 兼容模式使用：选择含 Scripts\\python.exe 的 venv；留空时使用 Kohya 环境。第三、第四引擎会管理自己的隔离环境。',
  resetPreset: '把当前模式+底模的所有参数恢复成推荐预设（手动改过的会被重置，风格预设也会重置为「自定义」）。',
  modelPath: '本地可选择完整 Diffusers 模型目录；Qwen-Image-2.1 还支持单文件权重，并可手动指定现有文本编码器和 VAE。',
  textEncoderPath: '选择本机已有的 Qwen-Image-2.1 文本编码器 safetensors 文件；留空时先自动查找，缺少时才准备。',
  vaePath: '选择本机已有的 Qwen-Image-2.1 VAE safetensors 文件；留空时先自动查找，缺少时才准备。',
  animaComponents: 'Anima 训练需要两个配套组件：Qwen3-0.6B 文本编码器（约 1.2GB）+ Qwen-Image VAE（约 0.3GB）。打开后可查看当前实际在用哪个、指定本机已有的文件，或恢复默认回到自动查找/下载。文本编码器请选择 Qwen3-0.6B 模型本身的文件夹（里面有 config.json），不要选 ComfyUI 的 models 大目录。',
  krea2Guide: '打开 Krea2 图像 LoRA 的详细逐步引导（安装环境、准备模型、选图、预处理、训练、出图与常见问题）。',
  flux2Guide: '打开 FLUX.2 图像 LoRA 的详细使用引导。',
  h3Guide: '打开 MiniMax H3 视频 LoRA 的详细引导（安装引擎、准备模型、视频与字幕、训练和出视频）。',
  oneClickTrain: '按当前模式检查和准备数据，再确认标签及训练设置后启动。图片模式可能进行筛选、去重和打标；媒体模式读取同名字幕。',
  engineUpdate: '当前训练引擎有可用更新。点击查看版本状态并启动引擎升级。',
} as const

export type LegacyTooltipKey = keyof typeof legacyTooltips
