/**
 * Help text carried forward from the classic CustomTkinter UI.
 * Keep parameter explanations aligned with kohya_core/configs.py PARAM_TIPS and
 * KohyaLoRATool._attach_main_tooltips / _attach_adv_tooltips.
 */
export const legacyTooltips = {
  mode: '训练模式：画风=只学绘画风格（不学脸/角色）；人物=学某个角色的脸、服饰、特征。切换会自动填好推荐参数。',
  atSubMode: '人物=保留全部标签；画风=过滤人物标签；概念=形态/种族（trigger 吸收原型）。',
  baseModel: '底模架构：SD1.5/SDXL 是经典架构；FLUX.1 画质新但非常吃显存（8G 不推荐）；Anima 是 2026 最新架构、显存友好。选择底模文件后会自动识别。',
  rawDir: '放原始图片的文件夹（支持 jpg/png/webp/bmp/tif/gif）。',
  chooseRawDir: '选择原始图片文件夹。',
  preprocess: '缩放/去黑边/去水印/打标签。一键开始训练会自动做，老手可单独用。',
  labelEditor: '打开标签编辑器：逐张看图改标签、批量删除/替换标签、置顶 trigger、标签频率统计、整理成 repeats_名称 子目录结构。训练前改好标签，模型学得更准。',
  openOutput: '打开训练产物目录：模型、使用模板、参数报告、中间快照。',
  readme: '打开新手教学 & 常见问题窗口。',
  modelHelp: '查看模型选择步骤、本地模型目录格式、训练流程和显存建议。',
  trigger: '触发词=模型的“召唤词”：人物模式=角色名；画风模式=画风专属词。训练后画图写上它就能唤出角色/画风。支持多个，用英文逗号分隔。',
  regDir: '正则图：同一角色的参考图文件夹，训练时防止模型学过头（可选）。',
  chooseRegDir: '选择正则数据集文件夹（人物模式可选）。',
  stylePreset: '出图风格：只在「模式+底模」基线学习率上做微调（动漫 ×0.85 更精细、写实 ×1.15 更自然）。rank / alpha / repeats / epoch 仍按训练模式和底模自动填；选「写实」还会切换打标兜底描述与成品文件名。',
  styleCaption: '留空=自动打标；填了用它（画风更准）。',
  conceptType: '选择要学习的概念类型；下方会显示该类型对应的数据集准备建议。',
  cleanConcept: '删掉描述这个概念本身的标签（如 black jacket / long sleeves / zipper），让触发词独占它。',
  strongBind: '自动把 trigger + 训练集 100% 一致的特征词固定到标签开头。',
  samplePreview: '训练中采样预览（用当前 LoRA 出预览图，频率见下方「采样预览间隔」；低显存自动关闭）。',
  samplePrompt: '留空=自动（trigger + portrait, masterpiece, best quality）；填了整句生效（是否带 trigger 自己定），不再被覆盖。',
  cropRatio: '默认不裁切（保比例，人脸不易被切）；可输入自定义宽:高，如 2:3。',
  wd14Model: '选择自动打标模型。首次使用会下载，之后离线可用。',
  overwrite: '勾选后：重新生成图片并重读你现在的标签（源文件夹里的 .txt）。\n不勾选（默认）：输出目录里已经处理过的图会整张跳过，你在源文件夹里改的标签不会被采用。\n\n什么时候需要勾：手动改过标签、用外部/别的打标模型重写过标签，或想换裁切比例 / 分辨率重新出图时。',
  rank: 'LoRA 秩：越大学得越细、越像，也越容易过拟合；一般 8~64。',
  alpha: '缩放系数：一般取 rank 的一半，影响 LoRA 的强度。',
  unet_lr: 'UNet 学习率：越大学得越快，太大容易崩或过拟合。',
  te_lr: '文本编码器学习率：控制提示词理解的学习速度，建议比 UNet 学习率低。',
  unetOnly: '只训练 UNet（不训练文本编码器）：更省显存、更稳，画风类可以勾选。',
  repeats: '每张图片重复次数：越多学得越用力，小心过拟合。',
  maxEpochs: '最大训练轮数：轮数越多学得越久，够用就好。',
  resolution: '训练分辨率：512 最省显存最快，768 平衡，1024 画质最好。16G 显存跑 Krea2/SDXL 建议降到 768 或 512，防止爆显存。',
  videoSteps: '视频 LoRA 总训练步数：2000 左右较稳；步数过高会死记视频内容（过拟合）。上限 3000。',
  videoFrames: 'H3 视频帧数需符合 17n+5 格式；例如 73 帧。',
  fastTier: '自动=按显存自动启用；开=强制快跑（低分辨率/省显存/关采样）；关=完全按常规参数。',
  optimizer: '自动=按环境预检选 AdamW8bit 或降级；若报 bitsandbytes 崩溃，改选 AdamW/Lion。Krea2/FLUX.2 的 Fizgig 引擎不支持此项，用引擎默认。',
  quantMode: '自动=int8；Krea2 的 fp8 明显更慢。',
  blocksToSwap: '自动=按显存档位；0=全部驻留显存；块越少越快但越吃显存。',
  compile: '第一引擎编译 U-Net；第二引擎编译 28 个块。编译需额外显存，<10G 自动禁用；Windows 下可能编译失败，慎开。',
  noiseOffset: '噪声偏移：训练时给随机噪声做一点调整，可能影响暗部和整体明暗对比。当前 0.05 是推荐值；新手保持不变即可。',
  minSnrGamma: 'Min-SNR gamma：平衡模型在不同训练噪声阶段的学习权重。当前 5 是推荐值；新手保持不变即可，它不是清晰度或训练轮数设置。',
  globalPos: '附加全局正向提示词：训练时自动加到每张图片标签最前面（例如 masterpiece），不写进图片的 txt 文件，可留空。',
  globalNeg: '附加全局负向提示词：会写进使用模板和参数报告；kohya 训练本身不使用负向提示词，可留空。',
  saveEverySteps: '画风/人物/视频/Qwen/Z-Image 按「步」保存；留空=默认 200 步。',
  saveEveryEpochs: '本引擎按「轮」保存：直接填轮数，填 1 = 每轮都存；留空=默认每 1 轮。填得比总轮数还大时，一次快照都不会存。',
  sampleIntervalSteps: '0/留空=默认：画风/人物/Krea2/FLUX.2 跟随保存快照，视频/Qwen/Z-Image 每 250 步；填 N=每 N 步出预览。',
  sampleIntervalEpochs: '本引擎按「轮」出图：直接填轮数，填 10 = 每 10 轮一次；留空=每 1 轮。它做不到「每 N 步」。',
  amdMode: 'AMD 兼容模式（实验性）：按当前引擎检查对应环境并使用 AMD 训练配置。第三引擎需安装独立 ROCm 环境；第一引擎可指定训练 venv。',
  trainEnv: '仅第一引擎 AMD 兼容模式使用：选择含 Scripts\\python.exe 的 venv；留空时使用 Kohya 环境。第三、第四引擎会管理自己的隔离环境。',
  resetPreset: '把当前模式+底模的所有参数恢复成推荐预设（手动改过的会被重置，风格预设也会重置为「自定义」）。',
  modelPath: '本地可选择完整 Diffusers 模型目录；Qwen-Image-2.1 还支持单文件权重，并可手动指定现有文本编码器和 VAE。',
  textEncoderPath: '选择本机已有的 Qwen-Image-2.1 文本编码器 safetensors 文件；留空时先自动查找，缺少时才准备。',
  vaePath: '选择本机已有的 Qwen-Image-2.1 VAE safetensors 文件；留空时先自动查找，缺少时才准备。',
  animaComponents: 'Anima 训练需要两个配套组件：Qwen3-0.6B 文本编码器（约 1.2GB）+ Qwen-Image VAE（约 0.3GB）。打开后可查看当前实际在用哪个、指定本机已有的文件，或恢复默认回到自动查找/下载。文本编码器请选择 Qwen3-0.6B 模型本身的文件夹（里面有 config.json），不要选 ComfyUI 的 models 大目录。',
  krea2Guide: '打开 Krea2 图像 LoRA 的详细逐步引导（安装环境、准备模型、选图、预处理、训练、出图与常见问题）。',
  flux2Guide: '打开 FLUX.2 图像 LoRA 的详细使用引导。',
  h3Guide: '打开 MiniMax H3 视频 LoRA 的详细引导（安装引擎、准备模型、视频与字幕、训练和出视频）。',
  oneClickTrain: '自动检查并过滤模糊或过小图片 → 去重 → 按裁切比例设置处理 → WD14 打标签 → 训练；点击后先处理数据，再确认训练参数。',
  engineUpdate: '当前 AI Toolkit 还没有 Qwen-Image-2.1 架构。点击查看更新并一键升级引擎。',
} as const

export type LegacyTooltipKey = keyof typeof legacyTooltips
